ig.countryCodes =
  SY   : "Sýrie"
  AF   : "Afghánistán"
  XK   : "Kosovo"
  ER   : "Eritrea"
  AL   : "Albánie"
  PK   : "Pakistán"
  RU   : "Rusko"
  IQ   : "Irák"
  RS   : "Srbsko"
  NG   : "Nigérie"
  SO   : "Somálsko"
  STLS : "Bez národnosti"
  IR   : "Írán"
  UA   : "Ukrajina"
  BD   : "Bangladéš"
  ML   : "Mali"
  GM   : "Gambie"
  MK   : "Makedonie"
  UNK  : "Neznámý"
  GE   : "Gruzie"
